## Part 1: Data loading and initial inspection

   1. Reading Files

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_excel('/content/Mobiles_Dataset.xlsx')

In [ ]:
df.head(5)

,Product Name,Actual price,Discount price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
0,"Apple iPhone 15 (Green, 128 GB)","₹79,600","₹65,999",4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...
1,"Apple iPhone 15 (Blue, 128 GB)","₹79,600","₹65,999",4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...
2,"Apple iPhone 15 (Black, 128 GB)","₹79,600","₹65,999",4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...
3,"OnePlus N20 SE (JADE WAVE, 128 GB)","₹19,999","₹11,489",4.0,"1,005 Ratings",41 Reviews,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)","₹16,999","₹12,999",4.0,"1,005 Ratings",41 Reviews,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...

In [ ]:
df.tail(3)

,Product Name,Actual price,Discount price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
981,Kechaoda A27,"₹1,499",₹975,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,NaN,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
982,Kechaoda A27,"₹1,499",₹930,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
983,Kechaoda A27,"₹1,499",₹967,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...

2. Basic info

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product Name         984 non-null    object
 1   Actual price         984 non-null    object
 2   Discount price       980 non-null    object
 3   Stars                984 non-null    float64
 4   Rating               984 non-null    object
 5   Reviews              984 non-null    object
 6   RAM (GB)             984 non-null    object
 7   Storage (GB)         984 non-null    object
 8   Display Size (inch)  984 non-null    float64
 9   Camera               908 non-null    object
 10  Description          984 non-null    object
 11  Link                 984 non-null    object
dtypes: float64(2), object(10)
memory usage: 92.4+ KB

In [ ]:
df.count()

Product Name           984
Actual price           984
Discount price         980
Stars                  984
Rating                 984
Reviews                984
RAM (GB)               984
Storage (GB)           984
Display Size (inch)    984
Camera                 908
Description            984
Link                   984
dtype: int64

3. Descriptive stats

In [ ]:
df.describe()

            Stars  Display Size (inch)
count  984.000000           984.000000
mean     4.254980             6.043116
std      0.199734             1.581261
min      3.400000             0.660000
25%      4.200000             6.500000
50%      4.300000             6.670000
75%      4.400000             6.720000
max      5.000000             7.820000

4. Sampling

In [ ]:
df.sample(10)

,Product Name,Actual price,Discount price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
828,"Apple iPhone 15 Plus (Black, 128 GB)","₹89,600","₹73,999",4.6,"7,658 Ratings",637 Reviews,NIL,128,6.70,48MP + 12MP,128 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-plus-...
476,"REDMI Note 13 5G (Chromatic Purple, 256 GB)","₹22,999","₹18,999",4.1,"5,620 Ratings",322 Reviews,8,256,6.67,108MP + 2MP,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB16...,https://www.flipkart.com/redmi-note-13-5g-chro...
243,"IQOO Z7 Pro 5G (Blue Lagoon, 256 GB)","₹27,999","₹23,999",4.4,"5,576 Ratings",342 Reviews,8,256,6.78,64MP + 2MP,8 GB RAM | 256 GB ROM17.22 cm (6.78 inch) Disp...,https://www.flipkart.com/iqoo-z7-pro-5g-blue-l...
112,"OPPO A59 5G (Starry Black, 128 GB)","₹19,999","₹15,499",4.3,"2,016 Ratings",103 Reviews,6,128,6.56,13MP + 2MP,6 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...,https://www.flipkart.com/oppo-a59-5g-starry-bl...
598,"realme 12 Pro+ 5G (Submarine Blue, 128 GB)","₹34,999","₹29,999",4.4,"17,356 Ratings","2,216 Reviews",8,128,6.70,50MP + 8MP,8 GB RAM | 128 GB ROM17.02 cm (6.7 inch) Full ...,https://www.flipkart.com/realme-12-pro-5g-subm...
540,"POCO C65 (Matte Black, 128 GB)","₹11,999","₹7,499",4.2,"12,773 Ratings",661 Reviews,6,128,6.74,2MP | 8MP,6 GB RAM | 128 GB ROM | Expandable Upto 1 TB17...,https://www.flipkart.com/poco-c65-matte-black-...
114,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Violet, ...","₹1,34,999","₹1,29,999",4.6,"1,896 Ratings",244 Reviews,12,256,6.80,200MP + 50MP,12 GB RAM | 256 GB ROM17.27 cm (6.8 inch) Quad...,https://www.flipkart.com/samsung-galaxy-s24-ul...
810,"REDMI A3 (Olive Green, 64 GB)","₹9,999","₹7,165",4.1,"2,254 Ratings",94 Reviews,3,64,6.71,8MP,3 GB RAM | 64 GB ROM | Expandable Upto 1 TB17....,https://www.flipkart.com/redmi-a3-olive-green-...
22,"realme 12 Pro+ 5G (Navigator Beige, 256 GB)","₹37,999","₹33,999",4.4,"5,815 Ratings",643 Reviews,12,256,6.70,50MP + 8MP,12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Full...,https://www.flipkart.com/realme-12-pro-5g-navi...
130,"IQOO Neo9 Pro (Conqueror Black, 256 GB)","₹44,999","₹41,999",4.5,292 Ratings,21 Reviews,12,256,6.78,50MP,12 GB RAM | 256 GB ROM17.22 cm (6.78 inch) Dis...,https://www.flipkart.com/iqoo-neo9-pro-conquer...

5. Rename Columns

In [ ]:
df = df.rename(columns= {'Actual price':'MRP','Discount price':'Selling_Price'})

## Part 2: Data cleaning & type conversion

6. String processing & astype

In [ ]:
df['MRP'] = df['MRP'].astype(str).str.replace('₹','').str.replace(',','').replace('NIL', np.nan).astype(float)                                                                            # By Aniket Maurya
df

,Product Name,MRP,Selling_Price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
0,"Apple iPhone 15 (Green, 128 GB)",79600.0,"₹65,999",4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...
1,"Apple iPhone 15 (Blue, 128 GB)",79600.0,"₹65,999",4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...
2,"Apple iPhone 15 (Black, 128 GB)",79600.0,"₹65,999",4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999.0,"₹11,489",4.0,"1,005 Ratings",41 Reviews,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999.0,"₹12,999",4.0,"1,005 Ratings",41 Reviews,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...
...,...,...,...,...,...,...,...,...,...,...,...,...
979,Kechaoda A27,1499.0,₹967,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
980,Kechaoda A27,1499.0,₹975,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,NaN,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
981,Kechaoda A27,1499.0,₹975,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,NaN,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
982,Kechaoda A27,1499.0,₹930,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
983,Kechaoda A27,1499.0,₹967,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...

In [ ]:
df['Selling_Price']= df['Selling_Price'].str.replace('₹','').str.replace(',','').replace('NIL', np.nan).astype(float)
df

,Product Name,MRP,Selling_Price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
0,"Apple iPhone 15 (Green, 128 GB)",79600.0,65999.0,4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...
1,"Apple iPhone 15 (Blue, 128 GB)",79600.0,65999.0,4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...
2,"Apple iPhone 15 (Black, 128 GB)",79600.0,65999.0,4.6,"44,793 Ratings","2,402 Reviews",NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999.0,11489.0,4.0,"1,005 Ratings",41 Reviews,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999.0,12999.0,4.0,"1,005 Ratings",41 Reviews,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...
...,...,...,...,...,...,...,...,...,...,...,...,...
979,Kechaoda A27,1499.0,967.0,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
980,Kechaoda A27,1499.0,975.0,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,NaN,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
981,Kechaoda A27,1499.0,975.0,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,NaN,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
982,Kechaoda A27,1499.0,930.0,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
983,Kechaoda A27,1499.0,967.0,4.0,"11,022 Ratings",693 Reviews,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...

In [ ]:
df['Rating'] = df['Rating'].replace(' Ratings','',regex=True).replace(',','',regex=True).astype(int)                                                                                                                                                                                    #By Aniket Maurya

In [ ]:
df['Reviews'] = df['Reviews'].replace(' Reviews','',regex= True).replace(',','',regex=True).astype(int)

In [ ]:
df

,Product Name,MRP,Selling_Price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
0,"Apple iPhone 15 (Green, 128 GB)",79600.0,65999.0,4.6,44793,2402,NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...
1,"Apple iPhone 15 (Blue, 128 GB)",79600.0,65999.0,4.6,44793,2402,NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...
2,"Apple iPhone 15 (Black, 128 GB)",79600.0,65999.0,4.6,44793,2402,NIL,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999.0,11489.0,4.0,1005,41,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999.0,12999.0,4.0,1005,41,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...
...,...,...,...,...,...,...,...,...,...,...,...,...
979,Kechaoda A27,1499.0,967.0,4.0,11022,693,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
980,Kechaoda A27,1499.0,975.0,4.0,11022,693,NIL,NIL,0.66,NaN,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
981,Kechaoda A27,1499.0,975.0,4.0,11022,693,NIL,NIL,0.66,NaN,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
982,Kechaoda A27,1499.0,930.0,4.0,11022,693,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
983,Kechaoda A27,1499.0,967.0,4.0,11022,693,NIL,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...

7. Handling missing values

In [ ]:
df['Camera'].isnull().sum()

np.int64(76)

In [ ]:
df.fillna({'Camera': 'Not specified'},inplace=True)

In [ ]:
df['Stars'].dropna(inplace=True)

8. Duplicates

In [ ]:
df.drop_duplicates(inplace=True)

9. Replace

In [ ]:
df['RAM (GB)'].replace('NIL','np.nan',inplace=True)

/tmp/ipython-input-3011668719.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['RAM (GB)'].replace('NIL','np.nan',inplace=True)

Part 3: Selecting, filtering & querying

10. loc vs iloc

In [ ]:
df.iloc[:10,:4]

                                 Product Name      MRP  Selling_Price  Stars
0             Apple iPhone 15 (Green, 128 GB)  79600.0        65999.0    4.6
1              Apple iPhone 15 (Blue, 128 GB)  79600.0        65999.0    4.6
2             Apple iPhone 15 (Black, 128 GB)  79600.0        65999.0    4.6
3          OnePlus N20 SE (JADE WAVE, 128 GB)  19999.0        11489.0    4.0
4          OnePlus N20 SE (BLUE OASIS, 64 GB)  16999.0        12999.0    4.0
5             OnePlus 12R (Cool Blue, 128 GB)  39999.0        38989.0    4.5
6  SAMSUNG Galaxy F14 5G (GOAT Green, 128 GB)  17490.0        10990.0    4.2
7       CMF by Nothing Phone 1 (Blue, 128 GB)  19999.0        15999.0    4.4
8       CMF by Nothing Phone 1 (Blue, 128 GB)  21999.0        17999.0    4.3
9       vivo Y200e 5G (Black Diamond, 128 GB)  25999.0        20999.0    4.3

In [ ]:
df.loc[df['Product Name'].str.contains('iPhone'),['Product Name','Selling_Price']]

                                 Product Name  Selling_Price
0             Apple iPhone 15 (Green, 128 GB)        65999.0
1              Apple iPhone 15 (Blue, 128 GB)        65999.0
2             Apple iPhone 15 (Black, 128 GB)        65999.0
28      Apple iPhone 15 Plus (Yellow, 128 GB)        73999.0
156     Apple iPhone 14 Plus (Purple, 512 GB)        86499.0
257    Apple iPhone 14 ((PRODUCT)RED, 128 GB)        59999.0
401       Apple iPhone 14 (Starlight, 128 GB)        59999.0
453  Apple iPhone 14 Plus (Starlight, 128 GB)        56499.0
492           Apple iPhone 15 (Green, 256 GB)        75999.0
493           Apple iPhone 15 (Green, 256 GB)        75999.0
581           Apple iPhone 15 (Black, 256 GB)        75999.0
582           Apple iPhone 15 (Black, 256 GB)        75999.0
583           Apple iPhone 15 (Black, 512 GB)        95999.0
641          Apple iPhone 15 (Yellow, 128 GB)        65999.0
642          Apple iPhone 15 (Yellow, 128 GB)        65999.0
751       Apple iPhone 15 Plus (Pink, 128 GB)        73999.0
752       Apple iPhone 14 Plus (Blue, 128 GB)        56499.0
753       Apple iPhone 14 Plus (Blue, 512 GB)        86499.0
760          Apple iPhone 14 (Purple, 128 GB)        59999.0
796            Apple iPhone 15 (Pink, 128 GB)        66499.0
800   Apple iPhone 14 Plus (Midnight, 128 GB)        56499.0
801   Apple iPhone 14 Plus (Midnight, 512 GB)        86499.0
819        Apple iPhone 14 (Midnight, 128 GB)        59999.0
820        Apple iPhone 14 (Midnight, 128 GB)        59999.0
828      Apple iPhone 15 Plus (Black, 128 GB)        73999.0
846      Apple iPhone 15 Plus (Green, 128 GB)        73999.0
903            Apple iPhone 14 (Blue, 128 GB)        59999.0
921       Apple iPhone 15 Plus (Blue, 128 GB)        73999.0
949           Apple iPhone 13 (Green, 128 GB)        52999.0
950           Apple iPhone 13 (Green, 128 GB)        52999.0
951           Apple iPhone 13 (Green, 128 GB)        52999.0
959        Apple iPhone 13 (Midnight, 128 GB)        52999.0
960       Apple iPhone 13 (Starlight, 128 GB)        52999.0
961            Apple iPhone 13 (Blue, 128 GB)        52999.0
962            Apple iPhone 13 (Blue, 256 GB)        59999.0
963            Apple iPhone 13 (Blue, 256 GB)        59999.0
968            Apple iPhone 12 (Blue, 128 GB)        44999.0
969            Apple iPhone 12 (Black, 64 GB)        38999.0
970           Apple iPhone 12 (Black, 256 GB)        52999.0

11. Boolean indexing & isin

In [ ]:
df['RAM (GB)'].isin([8,12])

0      False
1      False
2      False
3      False
4      False
       ...
979    False
980    False
981    False
982    False
983    False
Name: RAM (GB), Length: 984, dtype: bool

In [ ]:
df[(df['Stars'] > 4.5) & (df['Selling_Price'] < 50000)]                                                                                                                                         # By Aniket Maurya

,Product Name,MRP,Selling_Price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
256,"IQOO Z9 Lite 5G (?Aqua Flow, 128 GB)",14499.0,11065.0,4.7,7,0,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/iqoo-z9-lite-5g-aqua-...
386,"IQOO Z9 Lite 5G (Mocha Brown, 128 GB)",14499.0,11078.0,4.7,7,0,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/iqoo-z9-lite-5g-mocha...
968,"Apple iPhone 12 (Blue, 128 GB)",54900.0,44999.0,4.6,210470,13889,np.nan,128,6.10,12MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-12-blue-...
969,"Apple iPhone 12 (Black, 64 GB)",49900.0,38999.0,4.6,210470,13889,np.nan,64,6.10,12MP + 12MP,64 GB ROM15.49 cm (6.1 inch) Super Retina XDR ...,https://www.flipkart.com/apple-iphone-12-black...

12. Query

In [ ]:
df.query("`Product Name`.str.contains('SAMSUNG', case=False) & `Selling_Price` > 70000")

,Product Name,MRP,Selling_Price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link
39,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Black, 2...",134999.0,129999.0,4.6,1896,244,12,256,6.8,200MP + 50MP,12 GB RAM | 256 GB ROM17.27 cm (6.8 inch) Quad...,https://www.flipkart.com/samsung-galaxy-s24-ul...
114,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Violet, ...",134999.0,129999.0,4.6,1896,244,12,256,6.8,200MP + 50MP,12 GB RAM | 256 GB ROM17.27 cm (6.8 inch) Quad...,https://www.flipkart.com/samsung-galaxy-s24-ul...
154,"SAMSUNG Galaxy Z Fold6 5G (Silver Shadow, 256 GB)",NaN,164999.0,4.2,22,2,12,256,7.6,50MP + 12MP,12 GB RAM | 256 GB ROM19.3 cm (7.6 inch) QXGA+...,https://www.flipkart.com/samsung-galaxy-z-fold...
155,"SAMSUNG Galaxy Z Fold6 5G (Silver Shadow, 512 GB)",NaN,176999.0,4.2,22,2,12,512,7.6,50MP + 12MP,12 GB RAM | 512 GB ROM19.3 cm (7.6 inch) QXGA+...,https://www.flipkart.com/samsung-galaxy-z-fold...
169,"SAMSUNG Galaxy S24 5G (Onyx Black, 256 GB)",NaN,79999.0,4.5,1055,135,8,256,6.2,50MP + 10MP,8 GB RAM | 256 GB ROM15.75 cm (6.2 inch) Full ...,https://www.flipkart.com/samsung-galaxy-s24-5g...
281,"SAMSUNG Galaxy S24 5G (Amber Yellow, 256 GB)",NaN,79999.0,4.5,1055,135,8,256,6.2,50MP + 10MP,8 GB RAM | 256 GB ROM15.75 cm (6.2 inch) Full ...,https://www.flipkart.com/samsung-galaxy-s24-5g...
292,"SAMSUNG Galaxy S23 Ultra 5G (Cream, 256 GB)",149999.0,124999.0,4.6,3643,365,12,256,6.8,200MP + 10MP,12 GB RAM | 256 GB ROM17.27 cm (6.8 inch) Quad...,https://www.flipkart.com/samsung-galaxy-s23-ul...
508,"SAMSUNG Galaxy S24 5G (Cobalt Violet, 512 GB)",NaN,89999.0,4.5,1055,135,8,512,6.2,50MP + 10MP,8 GB RAM | 512 GB ROM15.75 cm (6.2 inch) Full ...,https://www.flipkart.com/samsung-galaxy-s24-5g...
542,"SAMSUNG Galaxy Z Flip6 5G (Silver Shadow, 256 GB)",NaN,109999.0,5.0,8,0,12,256,6.7,50MP + 12MP,12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Full...,https://www.flipkart.com/samsung-galaxy-z-flip...
543,"SAMSUNG Galaxy Z Flip6 5G (Silver Shadow, 256 GB)",NaN,109999.0,5.0,8,0,12,256,6.7,50MP + 12MP,12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Full...,https://www.flipkart.com/samsung-galaxy-z-flip...
636,"SAMSUNG Galaxy Z Flip6 5G (Blue, 256 GB)",NaN,109999.0,5.0,8,0,12,256,6.7,50MP + 12MP,12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Full...,https://www.flipkart.com/samsung-galaxy-z-flip...
695,"SAMSUNG Galaxy Z Fold6 5G (Navy, 256 GB)",NaN,164999.0,4.2,22,2,12,256,7.6,50MP + 12MP,12 GB RAM | 256 GB ROM19.3 cm (7.6 inch) QXGA+...,https://www.flipkart.com/samsung-galaxy-z-fold...
871,"SAMSUNG Galaxy S24 Ultra 5G (Titanium Gray, 25...",134999.0,129999.0,4.6,1896,244,12,256,6.8,200MP + 50MP,12 GB RAM | 256 GB ROM17.27 cm (6.8 inch) Quad...,https://www.flipkart.com/samsung-galaxy-s24-ul...
886,"SAMSUNG Galaxy S24+ 5G (Onyx Black, 256 GB)",NaN,99999.0,4.5,147,18,12,256,6.7,50MP + 10MP,12 GB RAM | 256 GB ROM17.02 cm (6.7 inch) Quad...,https://www.flipkart.com/samsung-galaxy-s24-5g...

13. Where

In [ ]:
df['Selling_Price'].where(df['Selling_Price']>20000, 0)

0      65999.0
1      65999.0
2      65999.0
3          0.0
4          0.0
        ...
979        0.0
980        0.0
981        0.0
982        0.0
983        0.0
Name: Selling_Price, Length: 984, dtype: float64

## Part 4: Advance Series and String operarions

14. value_count & unique

In [ ]:
df['Brand'] = df['Product Name'].str.split().str[0]

15. map

In [ ]:
conditions = [(df['Stars'] <= 3), (df['Stars'] <= 4)]         # By AM
df['Price_Category'] = np.select(conditions, ['Budget', 'Mid-Range'], default='Premium')
df

,Product Name,MRP,Selling_Price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link,Brand,Price_Category
0,"Apple iPhone 15 (Green, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...,Apple,Premium
1,"Apple iPhone 15 (Blue, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...,Apple,Premium
2,"Apple iPhone 15 (Black, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...,Apple,Premium
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999.0,11489.0,4.0,1005,41,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...,OnePlus,Mid-Range
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999.0,12999.0,4.0,1005,41,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...,OnePlus,Mid-Range
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range
980,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range
981,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range
982,Kechaoda A27,1499.0,930.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range
983,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range

16. apply & assign

In [ ]:
# Discount (Aniket Maurya) Percentage: $((MRP -Selling\_Price) / MRP) * 100$.

df['Discount_Percentage'] = ((df['MRP'] - df['Selling_Price']) / df['MRP']) * 100
df

,Product Name,MRP,Selling_Price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link,Brand,Price_Category,Discount_Percentage
0,"Apple iPhone 15 (Green, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...,Apple,Premium,17.086683
1,"Apple iPhone 15 (Blue, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...,Apple,Premium,17.086683
2,"Apple iPhone 15 (Black, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...,Apple,Premium,17.086683
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999.0,11489.0,4.0,1005,41,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...,OnePlus,Mid-Range,42.552128
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999.0,12999.0,4.0,1005,41,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...,OnePlus,Mid-Range,23.530796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,35.490327
980,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,34.956638
981,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,34.956638
982,Kechaoda A27,1499.0,930.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,37.958639
983,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,35.490327

17. std & mean

In [ ]:
df['Selling_Price'].std()

20843.490673786677

In [ ]:
df['Selling_Price'].mean()

np.float64(21524.401020408164)

## Part 5: Grouping & Aggregation

18. groupby & agg

In [ ]:
df.groupby('Brand')['Selling_Price'].agg( ['mean','sum','std'])

                   mean        sum           std
Brand
Apple      64883.615385  2530461.0  12294.875665
BlackZone   1569.000000     4707.0      0.000000
CMF        16999.000000   101994.0   1095.445115
Google     47732.333333   715985.0  12526.923386
Honor      24472.500000    48945.0   2089.500538
I           1630.000000     4890.0    399.713648
IQOO       18161.400000   363228.0   7205.046531
Infinix    12655.862745   645449.0   6527.978398
Jio         2344.500000     4689.0   1619.981636
KARBONN     1042.000000     9378.0    184.231512
Kechaoda    1100.150000    22003.0    196.409421
LAVA        3494.677419   108335.0   4211.469936
MOTOROLA    4355.666667    26134.0   3281.613424
Micromax    3504.750000    14019.0   4999.473264
Motorola   19036.931034  1104142.0  10908.066025
Nokia       3033.666667    91010.0   2159.950420
Nothing    27799.000000   277990.0   4589.843861
OPPO       20354.569444  1465529.0   9004.065176
OnePlus    36223.473684  1376492.0  25095.726362
POCO       15739.322581   975838.0   7765.876592
REDMI      16798.803922  1713478.0   8758.371087
SAMSUNG    37863.200000  3786320.0  38179.143187
Samsung    45999.000000    91998.0      0.000000
Tecno      13488.260870   310230.0   5665.143649
Vox          809.000000     1618.0      0.000000
Xiaomi     52374.000000   418992.0  11121.889613
itel        3632.425532   170724.0   2905.807152
realme     20420.766129  2532175.0   9794.082144
vivo       23924.835165  2177160.0  12609.533372

In [ ]:
df.groupby('Brand')['Selling_Price'].agg(['mean','sum','std'])

                   mean        sum           std
Brand
Apple      64883.615385  2530461.0  12294.875665
BlackZone   1569.000000     4707.0      0.000000
CMF        16999.000000   101994.0   1095.445115
Google     47732.333333   715985.0  12526.923386
Honor      24472.500000    48945.0   2089.500538
I           1630.000000     4890.0    399.713648
IQOO       18161.400000   363228.0   7205.046531
Infinix    12655.862745   645449.0   6527.978398
Jio         2344.500000     4689.0   1619.981636
KARBONN     1042.000000     9378.0    184.231512
Kechaoda    1100.150000    22003.0    196.409421
LAVA        3494.677419   108335.0   4211.469936
MOTOROLA    4355.666667    26134.0   3281.613424
Micromax    3504.750000    14019.0   4999.473264
Motorola   19036.931034  1104142.0  10908.066025
Nokia       3033.666667    91010.0   2159.950420
Nothing    27799.000000   277990.0   4589.843861
OPPO       20354.569444  1465529.0   9004.065176
OnePlus    36223.473684  1376492.0  25095.726362
POCO       15739.322581   975838.0   7765.876592
REDMI      16798.803922  1713478.0   8758.371087
SAMSUNG    37863.200000  3786320.0  38179.143187
Samsung    45999.000000    91998.0      0.000000
Tecno      13488.260870   310230.0   5665.143649
Vox          809.000000     1618.0      0.000000
Xiaomi     52374.000000   418992.0  11121.889613
itel        3632.425532   170724.0   2905.807152
realme     20420.766129  2532175.0   9794.082144
vivo       23924.835165  2177160.0  12609.533372

19. Transform

In [ ]:
df['Average_Brand_Price'] = df.groupby('Brand')['Selling_Price'].transform(lambda x:x.mean())           # By AM
df

,Product Name,MRP,Selling_Price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link,Brand,Price_Category,Discount_Percentage,Average_Brand_Price
0,"Apple iPhone 15 (Green, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...,Apple,Premium,17.086683,64883.615385
1,"Apple iPhone 15 (Blue, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...,Apple,Premium,17.086683,64883.615385
2,"Apple iPhone 15 (Black, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...,Apple,Premium,17.086683,64883.615385
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999.0,11489.0,4.0,1005,41,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...,OnePlus,Mid-Range,42.552128,36223.473684
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999.0,12999.0,4.0,1005,41,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...,OnePlus,Mid-Range,23.530796,36223.473684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,35.490327,1100.150000
980,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,34.956638,1100.150000
981,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,34.956638,1100.150000
982,Kechaoda A27,1499.0,930.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,37.958639,1100.150000
983,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,35.490327,1100.150000

20. Pivot table

In [ ]:
pivot_table = pd.pivot_table(df, values='Stars', index='Brand', columns='RAM (GB)', aggfunc='mean')
pivot_table

RAM (GB),2,3,4,6,8,12,16,32,46875,np.nan
Brand,,,,,,,,,,
Apple,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.600000
BlackZone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000
CMF,NaN,NaN,NaN,4.400000,4.300000,NaN,NaN,NaN,NaN,NaN
Google,NaN,NaN,NaN,NaN,4.171429,4.300000,NaN,NaN,NaN,NaN
Honor,NaN,NaN,NaN,NaN,4.200000,NaN,NaN,NaN,NaN,NaN
I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.833333
IQOO,NaN,NaN,4.340000,4.200000,4.380000,4.500000,NaN,NaN,NaN,NaN
Infinix,NaN,4.30,4.244444,NaN,4.200000,4.160000,NaN,NaN,NaN,NaN
Jio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.750000
KARBONN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.700000
Kechaoda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.020000
LAVA,NaN,NaN,4.100000,4.200000,4.140000,NaN,NaN,NaN,NaN,4.165217
MOTOROLA,NaN,NaN,4.200000,NaN,NaN,NaN,NaN,NaN,NaN,4.166667
Micromax,NaN,NaN,4.100000,NaN,NaN,NaN,NaN,NaN,NaN,3.933333
Motorola,4.000000,NaN,4.185714,4.100000,4.328000,4.326316,NaN,NaN,NaN,4.133333
Nokia,3.600000,NaN,3.800000,NaN,NaN,NaN,NaN,NaN,4.0,3.958333
Nothing,NaN,NaN,NaN,NaN,4.400000,4.400000,NaN,NaN,NaN,NaN
OPPO,NaN,NaN,4.287500,4.300000,4.346296,4.383333,NaN,NaN,NaN,NaN
OnePlus,NaN,NaN,4.000000,4.400000,4.400000,4.600000,4.53,NaN,NaN,NaN
POCO,NaN,NaN,4.186667,4.223077,4.211111,4.237500,NaN,NaN,NaN,NaN
REDMI,NaN,4.10,4.225926,4.172727,4.206452,4.180000,NaN,NaN,NaN,NaN
SAMSUNG,NaN,4.00,4.200000,4.205882,4.300000,4.528571,NaN,NaN,NaN,NaN
Samsung,NaN,NaN,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN
Tecno,NaN,4.15,4.233333,NaN,4.200000,4.200000,NaN,NaN,NaN,NaN
Vox,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.600000
Xiaomi,NaN,NaN,NaN,NaN,4.200000,4.400000,NaN,NaN,NaN,NaN
itel,3.866667,NaN,4.171429,NaN,4.100000,NaN,NaN,4.1,NaN,3.937037
realme,4.400000,NaN,4.168182,4.328571,4.321154,4.285000,4.50,NaN,NaN,NaN
vivo,NaN,4.20,4.353846,4.333333,4.412500,4.500000,4.70,NaN,NaN,NaN

21. Crosstab/count

In [ ]:
pd.crosstab(df['Brand'], df['Storage (GB)'])

Storage (GB)  0  3  4  5  16  32  64  125  128  256  512  NIL
Brand
Apple         0  0  0  0   0   0   1    0   27    7    4    0
BlackZone     0  0  0  0   0   0   0    0    0    0    0    3
CMF           0  0  0  0   0   0   0    0    6    0    0    0
Google        0  0  0  0   0   0   0    0   13    2    0    0
Honor         0  0  0  0   0   0   0    0    0    2    0    0
I             0  0  0  0   0   0   0    0    0    0    0    3
IQOO          0  0  0  0   0   0   0    0   15    5    0    0
Infinix       0  0  0  0   0   0  15    0   19   17    0    0
Jio           0  0  1  0   0   0   0    0    0    0    0    1
KARBONN       0  0  0  0   0   0   0    0    0    0    0    9
Kechaoda      0  0  0  0   2   1   0    0    0    0    0   17
LAVA          1  0  0  0   0   4   1    0    8    0    0   18
MOTOROLA      0  1  0  2   0   0   2    0    1    0    0    0
Micromax      0  0  0  0   0   0   0    0    1    0    0    3
Motorola      0  0  0  0   0   0   5    0   29   19    2    3
Nokia         0  0  0  0   0   0   1    2    3    0    0   24
Nothing       0  0  0  0   0   0   0    0    3    7    0    0
OPPO          0  0  0  0   0   0   3    0   22   46    1    0
OnePlus       0  0  0  0   0   0   1    0   20   12    5    0
POCO          0  0  0  0   0   0   6    0   24   24    8    0
REDMI         0  0  0  0   0   0   8    0   54   37    5    0
SAMSUNG       0  0  0  0   0   1  10    0   56   31    2    0
Samsung       0  0  0  0   0   0   0    0    2    0    0    0
Tecno         0  0  0  0   0   0   5    0    7   11    0    0
Vox           0  0  0  0   0   0   0    0    0    0    0    2
Xiaomi        0  0  0  0   0   0   0    0    0    2    6    0
itel          0  0  0  0   0   6   8    0    6    2    0   26
realme        0  0  0  0   0   1  10    0   68   37    8    0
vivo          0  0  0  0   0   2   2    0   61   23    3    0

## Part 6: Reshaping & Combining

22. Transpose & melt

In [ ]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,974,975,976,977,978,979,980,981,982,983
Product Name,"Apple iPhone 15 (Green, 128 GB)","Apple iPhone 15 (Blue, 128 GB)","Apple iPhone 15 (Black, 128 GB)","OnePlus N20 SE (JADE WAVE, 128 GB)","OnePlus N20 SE (BLUE OASIS, 64 GB)","OnePlus 12R (Cool Blue, 128 GB)","SAMSUNG Galaxy F14 5G (GOAT Green, 128 GB)","CMF by Nothing Phone 1 (Blue, 128 GB)","CMF by Nothing Phone 1 (Blue, 128 GB)","vivo Y200e 5G (Black Diamond, 128 GB)",...,LAVA A3 vibe,Kechaoda A26,Kechaoda A26,Kechaoda K115,Kechaoda A27,Kechaoda A27,Kechaoda A27,Kechaoda A27,Kechaoda A27,Kechaoda A27
MRP,79600.0,79600.0,79600.0,19999.0,16999.0,39999.0,17490.0,19999.0,21999.0,25999.0,...,1319.0,1499.0,1399.0,1350.0,1499.0,1499.0,1499.0,1499.0,1499.0,1499.0
Selling_Price,65999.0,65999.0,65999.0,11489.0,12999.0,38989.0,10990.0,15999.0,17999.0,20999.0,...,1212.0,930.0,999.0,1069.0,967.0,967.0,975.0,975.0,930.0,967.0
Stars,4.6,4.6,4.6,4.0,4.0,4.5,4.2,4.4,4.3,4.3,...,4.2,4.0,4.0,4.1,4.0,4.0,4.0,4.0,4.0,4.0
Rating,44793,44793,44793,1005,1005,4278,45538,8057,2355,687,...,21425,22244,22244,35912,11022,11022,11022,11022,11022,11022
Reviews,2402,2402,2402,41,41,292,2989,701,181,36,...,2247,1377,1377,2497,693,693,693,693,693,693
RAM (GB),np.nan,np.nan,np.nan,4,4,8,4,6,8,8,...,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan
Storage (GB),128,128,128,128,64,128,128,128,128,128,...,0,NIL,NIL,NIL,NIL,NIL,NIL,NIL,NIL,NIL
Display Size (inch),6.1,6.1,6.1,6.56,6.56,6.78,6.6,6.67,6.67,6.67,...,1.77,0.66,0.66,1.44,0.66,0.66,0.66,0.66,0.66,0.66
Camera,48MP + 12MP,48MP + 12MP,48MP + 12MP,50MP,50MP,50MP,50MP + 2MP,50MP + 2MP,50MP + 2MP,50MP + 2MP,...,3MP,0MP | 0MP,Not specified,3MP + 0MP,0MP | 0MP,0MP | 0MP,Not specified,Not specified,0MP | 0MP,0MP | 0MP
Description,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,8 GB RAM | 128 GB ROM17.22 cm (6.78 inch) Disp...,4 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...,6 GB RAM | 128 GB ROM | Expandable Upto 2 TB16...,8 GB RAM | 128 GB ROM | Expandable Upto 2 TB16...,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB16...,...,0 GB ROM | Expandable Upto 32 GB4.5 cm (1.77 i...,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,32 MB RAM | 32 MB ROM | Expandable Upto 32 GB3...,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...
Link,https://www.flipkart.com/apple-iphone-15-green...,https://www.flipkart.com/apple-iphone-15-blue-...,https://www.flipkart.com/apple-iphone-15-black...,https://www.flipkart.com/oneplus-n20-se-jade-w...,https://www.flipkart.com/oneplus-n20-se-blue-o...,https://www.flipkart.com/oneplus-12r-cool-blue...,https://www.flipkart.com/samsung-galaxy-f14-5g...,https://www.flipkart.com/cmf-nothing-phone-1-b...,https://www.flipkart.com/cmf-nothing-phone-1-b...,https://www.flipkart.com/vivo-y200e-5g-black-d...,...,https://www.flipkart.com/lava-a3-vibe/p/itmed3...,https://www.flipkart.com/kechaoda-a26/p/itmfcv...,https://www.flipkart.com/kechaoda-a26/p/itmfcv...,https://www.flipkart.com/kechaoda-k115/p/itmex...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...
Brand,Apple,Apple,Apple,OnePlus,OnePlus,OnePlus,SAMSUNG,CMF,CMF,vivo,...,LAVA,Kechaoda,Kechaoda,Kechaoda,Kechaoda,Kechaoda,Kechaoda,Kechaoda,Kechaoda,Kechaoda
Price_Category,Premium,Premium,Premium,Mid-Range,Mid-Range,Premium,Premium,Premium,Premium,Premium,...,Premium,Mid-Range,Mid-Range,Premium,Mid-Range,Mid-Range,Mid-Range,Mid-Range,Mid-Range,Mid-Range
Discount_Percentage,17.086683,17.086683,17.086683,42.552128,23.530796,2.525063,37.164094,20.001,18.182645,19.231509,...,8.112206,37.958639,28.591851,20.814815,35.490327,35.490327,34.956638,34.956638,37.958639,35.490327
Average_Brand_Price,64883.615385,64883.615385,64883.615385,36223.473684,36223.473684,36223.473684,37863.2,16999.0,16999.0,23924.835165,...,3494.677419,1100.15,1100.15,1100.15,1100.15,1100.15,1100.15,1100.15,1100.15,1100.15

In [ ]:
df.melt(id_vars='Product Name',value_vars=['Selling_Price','MRP'])

                            Product Name       variable    value
0        Apple iPhone 15 (Green, 128 GB)  Selling_Price  65999.0
1         Apple iPhone 15 (Blue, 128 GB)  Selling_Price  65999.0
2        Apple iPhone 15 (Black, 128 GB)  Selling_Price  65999.0
3     OnePlus N20 SE (JADE WAVE, 128 GB)  Selling_Price  11489.0
4     OnePlus N20 SE (BLUE OASIS, 64 GB)  Selling_Price  12999.0
...                                  ...            ...      ...
1963                        Kechaoda A27            MRP   1499.0
1964                        Kechaoda A27            MRP   1499.0
1965                        Kechaoda A27            MRP   1499.0
1966                        Kechaoda A27            MRP   1499.0
1967                        Kechaoda A27            MRP   1499.0

[1968 rows x 3 columns]

23. concat & merge

In [ ]:
df1 = df.iloc[:500]

In [ ]:
df2 = df.iloc[500:]

In [ ]:
pd.concat([df1,df2])

,Product Name,MRP,Selling_Price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,Description,Link,Brand,Price_Category,Discount_Percentage,Average_Brand_Price
0,"Apple iPhone 15 (Green, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-green...,Apple,Premium,17.086683,64883.615385
1,"Apple iPhone 15 (Blue, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-blue-...,Apple,Premium,17.086683,64883.615385
2,"Apple iPhone 15 (Black, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,https://www.flipkart.com/apple-iphone-15-black...,Apple,Premium,17.086683,64883.615385
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999.0,11489.0,4.0,1005,41,4,128,6.56,50MP,4 GB RAM | 128 GB ROM16.66 cm (6.56 inch) Disp...,https://www.flipkart.com/oneplus-n20-se-jade-w...,OnePlus,Mid-Range,42.552128,36223.473684
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999.0,12999.0,4.0,1005,41,4,64,6.56,50MP,4 GB RAM | 64 GB ROM16.66 cm (6.56 inch) Displ...,https://www.flipkart.com/oneplus-n20-se-blue-o...,OnePlus,Mid-Range,23.530796,36223.473684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,35.490327,1100.150000
980,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,34.956638,1100.150000
981,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,34.956638,1100.150000
982,Kechaoda A27,1499.0,930.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,37.958639,1100.150000
983,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB1...,https://www.flipkart.com/kechaoda-a27/p/itmfe3...,Kechaoda,Mid-Range,35.490327,1100.150000

In [ ]:
country_df = pd.DataFrame({'Brand': ['Apple', 'SAMSUNG','OnePlus'], 'Country': ['USA', 'South Korea','China']})
df_merged = df.merge(country_df, on='Brand', how='left')
df_merged

,Product Name,MRP,Selling_Price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,...,Price_Category,Discount_Percentage,Average_Brand_Price,Previous_Price,Launch_Date,Year,Month_Name,Day_of_Week,Launch_Period,Country
0,"Apple iPhone 15 (Green, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,...,Premium,17.086683,64883.615385,NaN,2023-01-01,2023,January,Sunday,2023-01,USA
1,"Apple iPhone 15 (Blue, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,...,Premium,17.086683,64883.615385,65999.0,2023-01-02,2023,January,Monday,2023-01,USA
2,"Apple iPhone 15 (Black, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,...,Premium,17.086683,64883.615385,65999.0,2023-01-03,2023,January,Tuesday,2023-01,USA
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999.0,11489.0,4.0,1005,41,4,128,6.56,50MP,...,Mid-Range,42.552128,36223.473684,65999.0,2023-01-04,2023,January,Wednesday,2023-01,China
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999.0,12999.0,4.0,1005,41,4,64,6.56,50MP,...,Mid-Range,23.530796,36223.473684,11489.0,2023-01-05,2023,January,Thursday,2023-01,China
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,...,Mid-Range,35.490327,1100.150000,967.0,2025-09-06,2025,September,Saturday,2025-09,NaN
980,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,...,Mid-Range,34.956638,1100.150000,967.0,2025-09-07,2025,September,Sunday,2025-09,NaN
981,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,...,Mid-Range,34.956638,1100.150000,975.0,2025-09-08,2025,September,Monday,2025-09,NaN
982,Kechaoda A27,1499.0,930.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,...,Mid-Range,37.958639,1100.150000,975.0,2025-09-09,2025,September,Tuesday,2025-09,NaN
983,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,...,Mid-Range,35.490327,1100.150000,930.0,2025-09-10,2025,September,Wednesday,2025-09,NaN

24. Shift

In [ ]:
df['Previous_Price'] = df['Selling_Price'].shift(1)

## Part 7: Time Series & Numpy

25. Date Creation

In [ ]:
df['Launch_Date'] = pd.date_range('2023-01-01', periods=len(df), freq='D')
df

,Product Name,MRP,Selling_Price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,...,Brand,Price_Category,Discount_Percentage,Average_Brand_Price,Previous_Price,Launch_Date,Year,Month_Name,Day_of_Week,Launch_Period
0,"Apple iPhone 15 (Green, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,...,Apple,Premium,17.086683,64883.615385,NaN,2023-01-01,2023,January,Sunday,2023-01
1,"Apple iPhone 15 (Blue, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,...,Apple,Premium,17.086683,64883.615385,65999.0,2023-01-02,2023,January,Monday,2023-01
2,"Apple iPhone 15 (Black, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,...,Apple,Premium,17.086683,64883.615385,65999.0,2023-01-03,2023,January,Tuesday,2023-01
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999.0,11489.0,4.0,1005,41,4,128,6.56,50MP,...,OnePlus,Mid-Range,42.552128,36223.473684,65999.0,2023-01-04,2023,January,Wednesday,2023-01
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999.0,12999.0,4.0,1005,41,4,64,6.56,50MP,...,OnePlus,Mid-Range,23.530796,36223.473684,11489.0,2023-01-05,2023,January,Thursday,2023-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,...,Kechaoda,Mid-Range,35.490327,1100.150000,967.0,2025-09-06,2025,September,Saturday,2025-09
980,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,...,Kechaoda,Mid-Range,34.956638,1100.150000,967.0,2025-09-07,2025,September,Sunday,2025-09
981,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,...,Kechaoda,Mid-Range,34.956638,1100.150000,975.0,2025-09-08,2025,September,Monday,2025-09
982,Kechaoda A27,1499.0,930.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,...,Kechaoda,Mid-Range,37.958639,1100.150000,975.0,2025-09-09,2025,September,Tuesday,2025-09
983,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,...,Kechaoda,Mid-Range,35.490327,1100.150000,930.0,2025-09-10,2025,September,Wednesday,2025-09

26. Date Accessors

In [ ]:
df['Year'] = df['Launch_Date'].dt.year
df['Month_Name'] = df['Launch_Date'].dt.month_name()
df['Day_of_Week'] = df['Launch_Date'].dt.day_name()
df

,Product Name,MRP,Selling_Price,Stars,Rating,Reviews,RAM (GB),Storage (GB),Display Size (inch),Camera,...,Brand,Price_Category,Discount_Percentage,Average_Brand_Price,Previous_Price,Launch_Date,Year,Month_Name,Day_of_Week,Launch_Period
0,"Apple iPhone 15 (Green, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,...,Apple,Premium,17.086683,64883.615385,NaN,2023-01-01,2023,January,Sunday,2023-01
1,"Apple iPhone 15 (Blue, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,...,Apple,Premium,17.086683,64883.615385,65999.0,2023-01-02,2023,January,Monday,2023-01
2,"Apple iPhone 15 (Black, 128 GB)",79600.0,65999.0,4.6,44793,2402,np.nan,128,6.10,48MP + 12MP,...,Apple,Premium,17.086683,64883.615385,65999.0,2023-01-03,2023,January,Tuesday,2023-01
3,"OnePlus N20 SE (JADE WAVE, 128 GB)",19999.0,11489.0,4.0,1005,41,4,128,6.56,50MP,...,OnePlus,Mid-Range,42.552128,36223.473684,65999.0,2023-01-04,2023,January,Wednesday,2023-01
4,"OnePlus N20 SE (BLUE OASIS, 64 GB)",16999.0,12999.0,4.0,1005,41,4,64,6.56,50MP,...,OnePlus,Mid-Range,23.530796,36223.473684,11489.0,2023-01-05,2023,January,Thursday,2023-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
979,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,...,Kechaoda,Mid-Range,35.490327,1100.150000,967.0,2025-09-06,2025,September,Saturday,2025-09
980,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,...,Kechaoda,Mid-Range,34.956638,1100.150000,967.0,2025-09-07,2025,September,Sunday,2025-09
981,Kechaoda A27,1499.0,975.0,4.0,11022,693,np.nan,NIL,0.66,Not specified,...,Kechaoda,Mid-Range,34.956638,1100.150000,975.0,2025-09-08,2025,September,Monday,2025-09
982,Kechaoda A27,1499.0,930.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,...,Kechaoda,Mid-Range,37.958639,1100.150000,975.0,2025-09-09,2025,September,Tuesday,2025-09
983,Kechaoda A27,1499.0,967.0,4.0,11022,693,np.nan,NIL,0.66,0MP | 0MP,...,Kechaoda,Mid-Range,35.490327,1100.150000,930.0,2025-09-10,2025,September,Wednesday,2025-09

27. Time periods

In [ ]:
df['Launch_Period'] = df['Launch_Date'].dt.to_period('M')

28. Numpy integration

In [ ]:
prices_array = df['Selling_Price'].to_numpy()
np.percentile(prices_array, 75)

np.float64(nan)

## Part 8: Exporting

In [ ]:
df.to_csv('mobiles_cleaned_final.csv', index=False)
df.to_excel('mobiles_cleaned_final.xlsx', index=False)

# By Aniket Maurya